### PR TITLE
Eclipse 4 6 compatibility

### PR DESCRIPTION
**Pull request by Wolfy42**
As every year eclipse did some breaking changes to their API.

This commits should migrate the WOLips-Plugin to Eclipse 4.6 compatibility without breaking the compatibility to eclipse versions before 4.6.

### CODE REVIEW

**Comment by Wolfy42** [comment]
Repeated tests on Eclipse 4.6 (Neon) RC1 and everything seems to work.

**Comment by nullterminated** [comment]
Thanks for being proactive! This is a first :D One question. Does this still work with 4.5 if merged now?

**Comment by Wolfy42** [comment]
Yes, I've also tested it against 4.5. 
It should also work in all Eclipse Java-IDE version starting at 4.2.

In all the upgrades I've just replaced old eclipse-code which is not supported anymore in the current eclipse e4 application platform. Every new version eclipse removes the support for some old eclipse e3 related code out of the compatibility layer. The compatibility layer is needed because wolips was developed against the e3 platform.

**Comment by Wolfy42** [comment]
Unfortunately the wolips-jenkins does not build anymore because of a small refactoring in this change.
I suspect the eclipse-version on jenkins is rather old, because I've checked that the new typesafe-method I've used exists since multiple versions.

But I'll open a new pull request with the usage of the old method so that no change on jenkins is necessary!

**Comment by darkv** [comment]
Looking at the jenkins configuration it seems that there is an Eclipse 4.4 installation. Currently I think there is only @pascalrobert who has access to that machine. Perhaps he can have a look at it if you know how to fix that server side issue?

**Comment by Wolfy42** [comment]
It's not a serverside issue. I've made a refactoring in the code because I wanted to get rid of some warnings. This refactoring resulted in the problem that although wolips would still run in old version of eclipse it would not be possible anymore to compile against some old version.

Although there is the question how many old versions of eclipse should be supported, there is no reason to drop some support just because of a small refactoring.

And it is rather complicated to prepare a new version of eclipse with jrebel and jprofiler-plugins included to compile against. So it would be unnecessary work to update the eclipse in the jenkins.

I'll open a new pull-request with the changes necessary to bring the build back to stable.

**Pull request merged**
