### PR TITLE
Support for Eclipse 4.26

### PR DESCRIPTION
**Pull request by lbane**
Adds support for Eclipse 4.26

The most glaring problem in Eclipse 4.26 is the deprecation and removal of the classes `BeansObservables` and `SWTObservables`. There are two replacement classes `BeanProperties` and `WidgetProperties` with similar functionality, but slightly different call syntax. The code got adjusted to use these classes.
A few additional compiler warnings are also fixed, but a lot more remain. I also propose to update the plugins for Java 11 compatibility, as this is the minimum version required by Eclipse.

In my testing the plugins run so far, without obvious more bugs than they already have. I'm not sure about backward compatibility, but in theory the "new" classes are already a few years old.

### CODE REVIEW

**Comment by nullterminated** [comment]
lol, I could have saved some time this weekend if I checked the PRs first. Your PR makes #173 redundant. I'm okay with it if yours is the winner here :)

**Comment by nullterminated** [comment]
It seems like commit https://github.com/wocommunity/wolips/pull/172/commits/2246b25c20bcd737e7433f85199a1734bd5ebb6f is causing issues with the build which is using an older version of Eclipse for the EclipseHome. My guess is either the referenced eclipse installation needs updating or this commit needs to rollback for the build to succeed.

**Comment by nullterminated** [comment]
It seems removing those changes did the trick and the build is working again. I might be a little ambitious, but feel free to resubmit them on a separate pr. We can add them when the eclipsehome is next updated.

**Comment by lbane** [comment]
> It seems like commit [2246b25](https://github.com/wocommunity/wolips/commit/2246b25c20bcd737e7433f85199a1734bd5ebb6f) is causing issues with the build which is using an older version of Eclipse for the EclipseHome. My guess is either the referenced eclipse installation needs updating or this commit needs to rollback for the build to succeed.

Which Eclipse version have you used?

**Comment by nullterminated** [comment]
No apologies or pre-announcing necessary. I'm glad to receive the contribution.

>Which Eclipse version have you used?

I'm using 2022-12, but the EclipseHome on the build server is something older. I'm not sure what it is. Based on the classpath of veogen when I started working on this also, it was something released on or after 2020.

**Pull request merged**
