### PR TITLE
EO model graph

### PR DESCRIPTION
**Pull request by rucotec**
Added a graphical editor for EOModels, still in its own branch but would be great if eventually integrated into standard WOLips

### CODE REVIEW

**Comment by rucotec** [comment]
Latest fixes are in

**Comment by nullterminated** [comment]
This is a pretty huge PR but I'll try to check out your branch and see if I can get it working on latest master sometime in the near future. Sounds pretty neat.

**Comment by nullterminated** [comment]
Only three years later, but we're still trying. I almost got this to compile for WOLips5. 
Unfortunately, it depends on JavaFX which was removed from the JDK a long while ago. I don't want to downgrade the project from JavaSE-21 to EOL'ed Java 1.8 just to bring this in.

I put the work on a branch that doesn't build, https://github.com/wocommunity/wolips/tree/pr_143

Perhaps it could be updated to work as an optional extension to EOModeler or you can find a way to bring JavaFX up to 21.

**Comment by rucotec** [comment]
Re JavaFX. I have just realized that there is openjfx.io which seems to work nicely with maven and even requires (!) Java21. Unfortunately I have not had any time to pursue this any further any and the guy who created the project has long since left. Oh my. . .

**Comment by nullterminated** [comment]
If anyone decides to pick this up and try to fix it, there are multiple concerns to make it something we can merge to wolips5.

1. JavaFX has native binaries which need to work with the five different product builds that wolips5 can do now.
2. It pulls in GEF plugins in order to work, which might bring along problems with it.
3. It integrates directly into EOModeler when it should probably add an extension point to modeler and be written as an optional extension because of 1 & 2.

I'll leave the PR/branch open in case anyone wants to tackle this, or ignore 1-3 and do it in their own fork of wolips.

**Pull request closed without merging**
